### ISSUE TITLE
About the OPR server

### ISSUE THREAD

**Issue by wong-hao** [OpenChirp/lorawan-service#3]
Dear sir,
   I read a paper of [Artur Balanuta](https://artur.balanuta.com/research/) at CMU: **A Cloud-Optimized Link Layer for Low-Power Wide-Area Networks**.
   I'm very interested in reproducing this paper, but I can't start with it because it is too abstract. From the author's [speech](https://www.youtube.com/watch?v=7Yv2q1auvK4), I seem to find that OPR has been applied to Openchirp of CMU. Is there anyway to observe the relevant source code or something like that?

**Comment by ABalanuta** [comment]
Hi @wong-hao,

The code in question has not been Open Sourced, and is not available to the general public yet.
